# Form implementation generated from reading ui file 'D:\KTLT\Cinema\Ui\Checkout.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CheckoutWindow(object):
    def setupUi(self, CheckoutWindow):
        CheckoutWindow.setObjectName("CheckoutWindow")
        CheckoutWindow.resize(1085, 784)
        CheckoutWindow.setMinimumSize(QtCore.QSize(1085, 784))
        CheckoutWindow.setStyleSheet("background-color: rgb(253, 253, 234);")
        self.checkout_area = QtWidgets.QWidget(parent=CheckoutWindow)
        self.checkout_area.setGeometry(QtCore.QRect(20, 50, 1031, 191))
        self.checkout_area.setStyleSheet("background-color:rgb(253, 253, 234)")
        self.checkout_area.setObjectName("checkout_area")
        self.frame = QtWidgets.QFrame(parent=self.checkout_area)
        self.frame.setGeometry(QtCore.QRect(20, 30, 151, 131))
        self.frame.setStyleSheet("background-color: rgb(251, 253, 218);\n"
"border-radius:20px;\n"
"border:1px solid rgb(247, 231, 199)")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(10, 20, 131, 111))
        self.label.setStyleSheet("border:0px;\n"
"background-color:transparent;")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("D:\\KTLT\\Cinema\\Ui\\../images/image-removebg-preview (56).png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.radioButton_cash = QtWidgets.QRadioButton(parent=self.frame)
        self.radioButton_cash.setGeometry(QtCore.QRect(110, 8, 31, 21))
        self.radioButton_cash.setStyleSheet("QRadioButton {\n"
"    font-size: 14px;\n"
"    color: #5b4c2b;\n"
"    padding: 4px 8px;\n"
"    spacing: 10px;\n"
"    background-color:transparent;\n"
"    border:0px;\n"
"}\n"
"QRadioButton::indicator {\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    border-radius: 8px; \n"
"    border: 2px solid rgb(195, 182, 157);     \n"
"    background-color: rgb(230, 215, 185);    \n"
"}\n"
"\n"
"QRadioButton::indicator:hover {\n"
"    border: 2px solid #c5a673;    \n"
"    background-color: #f6ebd3;     \n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color: #5b4c2b;     /* Nút tròn đậm khi đã chọn */\n"
"    border: 2px solid #5b4c2b;     /* Viền đậm khi đã chọn */\n"
"}\n"
"")
        self.radioButton_cash.setText("")
        self.radioButton_cash.setObjectName("radioButton_cash")
        self.frame_2 = QtWidgets.QFrame(parent=self.checkout_area)
        self.frame_2.setGeometry(QtCore.QRect(430, 30, 151, 131))
        self.frame_2.setStyleSheet("background-color: rgb(251, 253, 218);\n"
"border-radius:20px;\n"
"border:1px solid rgb(247, 231, 199)")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_2 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(25, 30, 101, 81))
        self.label_2.setStyleSheet("border:0px;\n"
"background-color:transparent;")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("D:\\KTLT\\Cinema\\Ui\\../images/img_5.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.radioButton_card = QtWidgets.QRadioButton(parent=self.frame_2)
        self.radioButton_card.setGeometry(QtCore.QRect(110, 8, 31, 21))
        self.radioButton_card.setStyleSheet("QRadioButton {\n"
"    font-size: 14px;\n"
"    color: #5b4c2b;\n"
"    padding: 4px 8px;\n"
"    spacing: 10px;\n"
"    background-color:transparent;\n"
"    border:0px;\n"
"}\n"
"QRadioButton::indicator {\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    border-radius: 8px; \n"
"    border: 2px solid rgb(195, 182, 157);     \n"
"    background-color: rgb(230, 215, 185);    \n"
"}\n"
"\n"
"QRadioButton::indicator:hover {\n"
"    border: 2px solid #c5a673;    \n"
"    background-color: #f6ebd3;     \n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color: #5b4c2b;     /* Nút tròn đậm khi đã chọn */\n"
"    border: 2px solid #5b4c2b;     /* Viền đậm khi đã chọn */\n"
"}\n"
"")
        self.radioButton_card.setText("")
        self.radioButton_card.setObjectName("radioButton_card")
        self.frame_3 = QtWidgets.QFrame(parent=self.checkout_area)
        self.frame_3.setGeometry(QtCore.QRect(850, 30, 151, 131))
        self.frame_3.setStyleSheet("background-color: rgb(251, 253, 218);\n"
"border-radius:20px;\n"
"border:1px solid rgb(247, 231, 199)")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_4 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_4.setGeometry(QtCore.QRect(30, 30, 111, 91))
        self.label_4.setStyleSheet("border:0px;\n"
"background-color:transparent;")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("D:\\KTLT\\Cinema\\Ui\\../images/img_6.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.radioButton_vnpay = QtWidgets.QRadioButton(parent=self.frame_3)
        self.radioButton_vnpay.setGeometry(QtCore.QRect(110, 8, 31, 21))
        self.radioButton_vnpay.setStyleSheet("QRadioButton {\n"
"    font-size: 14px;\n"
"    color: #5b4c2b;\n"
"    padding: 4px 8px;\n"
"    spacing: 10px;\n"
"    background-color:transparent;\n"
"    border:0px;\n"
"}\n"
"QRadioButton::indicator {\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    border-radius: 8px; \n"
"    border: 2px solid rgb(195, 182, 157);     \n"
"    background-color: rgb(230, 215, 185);    \n"
"}\n"
"\n"
"QRadioButton::indicator:hover {\n"
"    border: 2px solid #c5a673;    \n"
"    background-color: #f6ebd3;     \n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color: #5b4c2b;     /* Nút tròn đậm khi đã chọn */\n"
"    border: 2px solid #5b4c2b;     /* Viền đậm khi đã chọn */\n"
"}\n"
"")
        self.radioButton_vnpay.setText("")
        self.radioButton_vnpay.setObjectName("radioButton_vnpay")
        self.order_detail_area = QtWidgets.QWidget(parent=CheckoutWindow)
        self.order_detail_area.setGeometry(QtCore.QRect(20, 270, 1031, 461))
        self.order_detail_area.setStyleSheet("background-color:rgb(230, 215, 185); \n"
"border-radius:20px;")
        self.order_detail_area.setObjectName("order_detail_area")
        self.label_order_summary = QtWidgets.QLabel(parent=self.order_detail_area)
        self.label_order_summary.setGeometry(QtCore.QRect(20, 20, 320, 30))
        self.label_order_summary.setObjectName("label_order_summary")
        self.order_summary_content = QtWidgets.QTextEdit(parent=self.order_detail_area)
        self.order_summary_content.setGeometry(QtCore.QRect(20, 60, 991, 251))
        self.order_summary_content.setReadOnly(True)
        self.order_summary_content.setObjectName("order_summary_content")
        self.label_total = QtWidgets.QLabel(parent=self.order_detail_area)
        self.label_total.setGeometry(QtCore.QRect(20, 360, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_total.setFont(font)
        self.label_total.setObjectName("label_total")
        self.label_discount = QtWidgets.QLabel(parent=self.order_detail_area)
        self.label_discount.setGeometry(QtCore.QRect(20, 330, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(10)
        self.label_discount.setFont(font)
        self.label_discount.setObjectName("label_discount")
        self.lineEdit_discount = QtWidgets.QLineEdit(parent=self.order_detail_area)
        self.lineEdit_discount.setGeometry(QtCore.QRect(810, 330, 201, 22))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(10)
        self.lineEdit_discount.setFont(font)
        self.lineEdit_discount.setObjectName("lineEdit_discount")
        self.lineEdit_total = QtWidgets.QLineEdit(parent=self.order_detail_area)
        self.lineEdit_total.setGeometry(QtCore.QRect(810, 360, 201, 22))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(10)
        self.lineEdit_total.setFont(font)
        self.lineEdit_total.setObjectName("lineEdit_total")
        self.pushButton = QtWidgets.QPushButton(parent=self.order_detail_area)
        self.pushButton.setGeometry(QtCore.QRect(390, 410, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("\n"
"\n"
"QPushButton {\n"
"            background-color:rgb(253, 253, 234);\n"
"            color: rgb(91, 76, 43);\n"
"            \n"
"            border-radius: 20px;\n"
"            padding: 10px;\n"
"            font-size: 16px;\n"
"        }\n"
"        QPushButton:hover {\n"
"            background-color: rgb(216, 203, 164);\n"
"        }")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_Back = QtWidgets.QPushButton(parent=CheckoutWindow)
        self.pushButton_Back.setGeometry(QtCore.QRect(20, 30, 25, 25))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Back.setFont(font)
        self.pushButton_Back.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.pushButton_Back.setAutoFillBackground(False)
        self.pushButton_Back.setStyleSheet("QPushButton {\n"
"    min-width: 25px;\n"
"    min-height: 25px;\n"
"    max-width: 25px;\n"
"    max-height: 25px;\n"
"    border-radius: 10px; \n"
"    background-color: transparent;\n"
"    color: rgb(173, 162, 139);\n"
"    border: none;\n"
"    qproperty-alignment: \'AlignCenter\';\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 255, 240);\n"
"    min-width: 25px;\n"
"    min-height: 25px;\n"
"    max-width: 25px;\n"
"    max-height: 25px;\n"
"    border-radius: 10px;\n"
"    qproperty-alignment: \'AlignCenter\'; \n"
"}\n"
"")
        self.pushButton_Back.setText("◀")
        self.pushButton_Back.setObjectName("pushButton_Back")
        self.label_payment_method = QtWidgets.QLabel(parent=CheckoutWindow)
        self.label_payment_method.setGeometry(QtCore.QRect(51, 26, 320, 30))
        self.label_payment_method.setObjectName("label_payment_method")

        self.retranslateUi(CheckoutWindow)
        QtCore.QMetaObject.connectSlotsByName(CheckoutWindow)

    def retranslateUi(self, CheckoutWindow):
        _translate = QtCore.QCoreApplication.translate
        CheckoutWindow.setWindowTitle(_translate("CheckoutWindow", "Checkout"))
        self.label_order_summary.setStyleSheet(_translate("CheckoutWindow", "font-size: 16px; font-weight: bold; color: #5b4c2b;"))
        self.label_order_summary.setText(_translate("CheckoutWindow", "Order Deails:"))
        self.order_summary_content.setStyleSheet(_translate("CheckoutWindow", "background-color: #fdfae6; border: 1px solid #d8c49c; border-radius: 8px; padding: 6px; font-size: 13px; color: #5b4c2b;"))
        self.label_total.setText(_translate("CheckoutWindow", "Total:"))
        self.label_discount.setText(_translate("CheckoutWindow", "Discount:"))
        self.pushButton.setText(_translate("CheckoutWindow", "Done"))
        self.label_payment_method.setStyleSheet(_translate("CheckoutWindow", "font-size: 16px; font-weight: bold; color: #5b4c2b;"))
        self.label_payment_method.setText(_translate("CheckoutWindow", "PAYMENT METHOD"))
