# Form implementation generated from reading ui file 'D:\FinalProject\Ui\Checkout.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CheckoutWindow(object):
    def setupUi(self, CheckoutWindow):
        CheckoutWindow.setObjectName("CheckoutWindow")
        CheckoutWindow.resize(1127, 1013)
        CheckoutWindow.setMinimumSize(QtCore.QSize(1085, 784))
        CheckoutWindow.setStyleSheet("background-color: rgb(253, 253, 234);")
        self.checkout_area = QtWidgets.QWidget(parent=CheckoutWindow)
        self.checkout_area.setGeometry(QtCore.QRect(340, 10, 440, 191))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkout_area.sizePolicy().hasHeightForWidth())
        self.checkout_area.setSizePolicy(sizePolicy)
        self.checkout_area.setStyleSheet("background-color:rgb(253, 253, 234)")
        self.checkout_area.setObjectName("checkout_area")
        self.frame = QtWidgets.QFrame(parent=self.checkout_area)
        self.frame.setGeometry(QtCore.QRect(20, 30, 151, 131))
        self.frame.setStyleSheet("background-color: rgb(251, 253, 218);\n"
"border-radius:20px;\n"
"border:1px solid rgb(247, 231, 199)")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(10, 20, 131, 111))
        self.label.setStyleSheet("border:0px;\n"
"background-color:transparent;")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("D:\\FinalProject\\Ui\\../images/image-removebg-preview (56).png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.radioButton_cash = QtWidgets.QRadioButton(parent=self.frame)
        self.radioButton_cash.setGeometry(QtCore.QRect(110, 8, 31, 21))
        self.radioButton_cash.setStyleSheet("QRadioButton {\n"
"    font-size: 14px;\n"
"    color: #5b4c2b;\n"
"    padding: 4px 8px;\n"
"    spacing: 10px;\n"
"    background-color:transparent;\n"
"    border:0px;\n"
"}\n"
"QRadioButton::indicator {\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    border-radius: 8px; \n"
"    border: 2px solid rgb(195, 182, 157);     \n"
"    background-color: rgb(230, 215, 185);    \n"
"}\n"
"\n"
"QRadioButton::indicator:hover {\n"
"    border: 2px solid #c5a673;    \n"
"    background-color: #f6ebd3;     \n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color: #5b4c2b;     /* Nút tròn đậm khi đã chọn */\n"
"    border: 2px solid #5b4c2b;     /* Viền đậm khi đã chọn */\n"
"}\n"
"")
        self.radioButton_cash.setText("")
        self.radioButton_cash.setObjectName("radioButton_cash")
        self.frame_3 = QtWidgets.QFrame(parent=self.checkout_area)
        self.frame_3.setGeometry(QtCore.QRect(190, 30, 151, 131))
        self.frame_3.setStyleSheet("background-color: rgb(251, 253, 218);\n"
"border-radius:20px;\n"
"border:1px solid rgb(247, 231, 199)")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_4 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_4.setGeometry(QtCore.QRect(30, 30, 111, 91))
        self.label_4.setStyleSheet("border:0px;\n"
"background-color:transparent;")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("D:\\FinalProject\\Ui\\../images/img_6.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.radioButtonOnlinePay = QtWidgets.QRadioButton(parent=self.frame_3)
        self.radioButtonOnlinePay.setGeometry(QtCore.QRect(110, 8, 31, 21))
        self.radioButtonOnlinePay.setStyleSheet("QRadioButton {\n"
"    font-size: 14px;\n"
"    color: #5b4c2b;\n"
"    padding: 4px 8px;\n"
"    spacing: 10px;\n"
"    background-color:transparent;\n"
"    border:0px;\n"
"}\n"
"QRadioButton::indicator {\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    border-radius: 8px; \n"
"    border: 2px solid rgb(195, 182, 157);     \n"
"    background-color: rgb(230, 215, 185);    \n"
"}\n"
"\n"
"QRadioButton::indicator:hover {\n"
"    border: 2px solid #c5a673;    \n"
"    background-color: #f6ebd3;     \n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color: #5b4c2b;     /* Nút tròn đậm khi đã chọn */\n"
"    border: 2px solid #5b4c2b;     /* Viền đậm khi đã chọn */\n"
"}\n"
"")
        self.radioButtonOnlinePay.setText("")
        self.radioButtonOnlinePay.setObjectName("radioButtonOnlinePay")
        self.pushButton_Back = QtWidgets.QPushButton(parent=CheckoutWindow)
        self.pushButton_Back.setGeometry(QtCore.QRect(20, 14, 25, 25))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Back.setFont(font)
        self.pushButton_Back.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.pushButton_Back.setAutoFillBackground(False)
        self.pushButton_Back.setStyleSheet("QPushButton {\n"
"    min-width: 25px;\n"
"    min-height: 25px;\n"
"    max-width: 25px;\n"
"    max-height: 25px;\n"
"    border-radius: 10px; \n"
"    background-color: transparent;\n"
"    color: rgb(173, 162, 139);\n"
"    border: none;\n"
"    qproperty-alignment: \'AlignCenter\';\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 255, 240);\n"
"    min-width: 25px;\n"
"    min-height: 25px;\n"
"    max-width: 25px;\n"
"    max-height: 25px;\n"
"    border-radius: 10px;\n"
"    qproperty-alignment: \'AlignCenter\'; \n"
"}\n"
"")
        self.pushButton_Back.setText("◀")
        self.pushButton_Back.setObjectName("pushButton_Back")
        self.label_payment_method = QtWidgets.QLabel(parent=CheckoutWindow)
        self.label_payment_method.setGeometry(QtCore.QRect(50, 10, 171, 30))
        self.label_payment_method.setObjectName("label_payment_method")
        self.scrollArea = QtWidgets.QScrollArea(parent=CheckoutWindow)
        self.scrollArea.setGeometry(QtCore.QRect(40, 190, 1051, 651))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1049, 649))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.scrollLayout.setContentsMargins(10, 10, 10, 10)
        self.scrollLayout.setSpacing(10)
        self.scrollLayout.setObjectName("scrollLayout")
        self.order_detail_area = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents)
        self.order_detail_area.setStyleSheet("background-color:rgb(230, 215, 185);\n"
"border-radius:20px;")
        self.order_detail_area.setObjectName("order_detail_area")
        self.orderDetailLayout = QtWidgets.QVBoxLayout(self.order_detail_area)
        self.orderDetailLayout.setContentsMargins(10, 10, 10, 10)
        self.orderDetailLayout.setSpacing(10)
        self.orderDetailLayout.setObjectName("orderDetailLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.orderDetailLayout.addItem(spacerItem)
        self.label_order_summary = QtWidgets.QLabel(parent=self.order_detail_area)
        self.label_order_summary.setObjectName("label_order_summary")
        self.orderDetailLayout.addWidget(self.label_order_summary)
        self.scrollArea_OrderDetail = QtWidgets.QScrollArea(parent=self.order_detail_area)
        self.scrollArea_OrderDetail.setStyleSheet("QScrollBar:vertical {\n"
"    background: transparent;\n"
"    width: 8px;\n"
"    margin: 0px;\n"
"    border: none;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: transparent; /* xám nhạt */\n"
"    border-radius: 4px;\n"
"    min-height: 20px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"    background: none;\n"
"    height: 0px;\n"
"    border: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: transparent;\n"
"}\n"
"")
        self.scrollArea_OrderDetail.setWidgetResizable(True)
        self.scrollArea_OrderDetail.setObjectName("scrollArea_OrderDetail")
        self.scrollAreaWidgetContents_OrderDetail = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_OrderDetail.setGeometry(QtCore.QRect(0, 0, 1001, 210))
        self.scrollAreaWidgetContents_OrderDetail.setObjectName("scrollAreaWidgetContents_OrderDetail")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_OrderDetail)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.order_summary_content = QtWidgets.QTextEdit(parent=self.scrollAreaWidgetContents_OrderDetail)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.order_summary_content.sizePolicy().hasHeightForWidth())
        self.order_summary_content.setSizePolicy(sizePolicy)
        self.order_summary_content.setReadOnly(True)
        self.order_summary_content.setObjectName("order_summary_content")
        self.horizontalLayout.addWidget(self.order_summary_content)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.scrollArea_OrderDetail.setWidget(self.scrollAreaWidgetContents_OrderDetail)
        self.orderDetailLayout.addWidget(self.scrollArea_OrderDetail)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.orderDetailLayout.addItem(spacerItem1)
        self.label_total = QtWidgets.QLabel(parent=self.order_detail_area)
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_total.setFont(font)
        self.label_total.setObjectName("label_total")
        self.orderDetailLayout.addWidget(self.label_total)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.orderDetailLayout.addItem(spacerItem2)
        self.label_2 = QtWidgets.QLabel(parent=self.order_detail_area)
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.orderDetailLayout.addWidget(self.label_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.orderDetailLayout.addItem(spacerItem3)
        self.label_3 = QtWidgets.QLabel(parent=self.order_detail_area)
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.orderDetailLayout.addWidget(self.label_3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.orderDetailLayout.addItem(spacerItem4)
        self.label_5 = QtWidgets.QLabel(parent=self.order_detail_area)
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.orderDetailLayout.addWidget(self.label_5)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.orderDetailLayout.addItem(spacerItem5)
        self.label_6 = QtWidgets.QLabel(parent=self.order_detail_area)
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.orderDetailLayout.addWidget(self.label_6)
        self.lineEditTotal = QtWidgets.QLineEdit(parent=self.order_detail_area)
        self.lineEditTotal.setObjectName("lineEditTotal")
        self.orderDetailLayout.addWidget(self.lineEditTotal)
        self.pushButtonDone = QtWidgets.QPushButton(parent=self.order_detail_area)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButtonDone.setFont(font)
        self.pushButtonDone.setStyleSheet("\n"
"QPushButton {\n"
"            background-color:rgb(253, 253, 234);\n"
"            color: rgb(91, 76, 43);\n"
"            border-radius: 20px;\n"
"            border: 5px solid transparent ; \n"
"            padding: 10px;\n"
"            font-size: 16px;\n"
"        }\n"
"        QPushButton:hover {\n"
"            background-color: rgb(216, 203, 164);\n"
"        }")
        self.pushButtonDone.setObjectName("pushButtonDone")
        self.orderDetailLayout.addWidget(self.pushButtonDone)
        self.scrollLayout.addWidget(self.order_detail_area)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(CheckoutWindow)
        QtCore.QMetaObject.connectSlotsByName(CheckoutWindow)

    def retranslateUi(self, CheckoutWindow):
        _translate = QtCore.QCoreApplication.translate
        CheckoutWindow.setWindowTitle(_translate("CheckoutWindow", "Checkout"))
        self.label_payment_method.setStyleSheet(_translate("CheckoutWindow", "font-size: 16px; font-weight: bold; color: #5b4c2b;"))
        self.label_payment_method.setText(_translate("CheckoutWindow", "PAYMENT METHOD"))
        self.label_order_summary.setStyleSheet(_translate("CheckoutWindow", "font-size: 16px; font-weight: bold; color: #5b4c2b;"))
        self.label_order_summary.setText(_translate("CheckoutWindow", "Order Details:"))
        self.order_summary_content.setStyleSheet(_translate("CheckoutWindow", "background-color: #fdfae6; border: 1px solid #d8c49c; border-radius: 8px; padding: 6px; font-size: 13px; color: #5b4c2b;"))
        self.label_total.setText(_translate("CheckoutWindow", "Total:"))
        self.label_2.setText(_translate("CheckoutWindow", "Customer Name:"))
        self.label_3.setText(_translate("CheckoutWindow", "Customer Phone Numbers:"))
        self.label_5.setText(_translate("CheckoutWindow", "Customer Email:"))
        self.label_6.setText(_translate("CheckoutWindow", "Customer Address:"))
        self.pushButtonDone.setText(_translate("CheckoutWindow", "Done"))
