# Form implementation generated from reading ui file 'E:\Git_TDLT\FinalProject\Ui\Checkout.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CheckoutWindow(object):
    def setupUi(self, CheckoutWindow):
        CheckoutWindow.setObjectName("CheckoutWindow")
        CheckoutWindow.resize(1127, 924)
        CheckoutWindow.setMinimumSize(QtCore.QSize(1085, 784))
        CheckoutWindow.setStyleSheet("background-color: rgb(253, 253, 234);")
        self.checkout_area = QtWidgets.QWidget(parent=CheckoutWindow)
        self.checkout_area.setGeometry(QtCore.QRect(340, 10, 391, 171))
        self.checkout_area.setStyleSheet("background-color:rgb(253, 253, 234)")
        self.checkout_area.setObjectName("checkout_area")
        self.frame = QtWidgets.QFrame(parent=self.checkout_area)
        self.frame.setGeometry(QtCore.QRect(20, 30, 151, 131))
        self.frame.setStyleSheet("background-color: rgb(251, 253, 218);\n"
"border-radius:20px;\n"
"border:1px solid rgb(247, 231, 199)")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(10, 20, 131, 111))
        self.label.setStyleSheet("border:0px;\n"
"background-color:transparent;")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("E:\\Git_TDLT\\FinalProject\\Ui\\../images/image-removebg-preview (56).png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.radioButton_cash = QtWidgets.QRadioButton(parent=self.frame)
        self.radioButton_cash.setGeometry(QtCore.QRect(110, 8, 31, 21))
        self.radioButton_cash.setStyleSheet("QRadioButton {\n"
"    font-size: 14px;\n"
"    color: #5b4c2b;\n"
"    padding: 4px 8px;\n"
"    spacing: 10px;\n"
"    background-color:transparent;\n"
"    border:0px;\n"
"}\n"
"QRadioButton::indicator {\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    border-radius: 8px; \n"
"    border: 2px solid rgb(195, 182, 157);     \n"
"    background-color: rgb(230, 215, 185);    \n"
"}\n"
"\n"
"QRadioButton::indicator:hover {\n"
"    border: 2px solid #c5a673;    \n"
"    background-color: #f6ebd3;     \n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color: #5b4c2b;     /* Nút tròn đậm khi đã chọn */\n"
"    border: 2px solid #5b4c2b;     /* Viền đậm khi đã chọn */\n"
"}\n"
"")
        self.radioButton_cash.setText("")
        self.radioButton_cash.setObjectName("radioButton_cash")
        self.frame_3 = QtWidgets.QFrame(parent=self.checkout_area)
        self.frame_3.setGeometry(QtCore.QRect(210, 30, 151, 131))
        self.frame_3.setStyleSheet("background-color: rgb(251, 253, 218);\n"
"border-radius:20px;\n"
"border:1px solid rgb(247, 231, 199)")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_4 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_4.setGeometry(QtCore.QRect(30, 30, 111, 91))
        self.label_4.setStyleSheet("border:0px;\n"
"background-color:transparent;")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("E:\\Git_TDLT\\FinalProject\\Ui\\../images/img_6.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.radioButtonOnlinePay = QtWidgets.QRadioButton(parent=self.frame_3)
        self.radioButtonOnlinePay.setGeometry(QtCore.QRect(110, 8, 31, 21))
        self.radioButtonOnlinePay.setStyleSheet("QRadioButton {\n"
"    font-size: 14px;\n"
"    color: #5b4c2b;\n"
"    padding: 4px 8px;\n"
"    spacing: 10px;\n"
"    background-color:transparent;\n"
"    border:0px;\n"
"}\n"
"QRadioButton::indicator {\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    border-radius: 8px; \n"
"    border: 2px solid rgb(195, 182, 157);     \n"
"    background-color: rgb(230, 215, 185);    \n"
"}\n"
"\n"
"QRadioButton::indicator:hover {\n"
"    border: 2px solid #c5a673;    \n"
"    background-color: #f6ebd3;     \n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color: #5b4c2b;     /* Nút tròn đậm khi đã chọn */\n"
"    border: 2px solid #5b4c2b;     /* Viền đậm khi đã chọn */\n"
"}\n"
"")
        self.radioButtonOnlinePay.setText("")
        self.radioButtonOnlinePay.setObjectName("radioButtonOnlinePay")
        self.order_detail_area = QtWidgets.QWidget(parent=CheckoutWindow)
        self.order_detail_area.setGeometry(QtCore.QRect(30, 180, 1031, 731))
        self.order_detail_area.setStyleSheet("background-color:rgb(230, 215, 185); \n"
"border-radius:20px;")
        self.order_detail_area.setObjectName("order_detail_area")
        self.label_order_summary = QtWidgets.QLabel(parent=self.order_detail_area)
        self.label_order_summary.setGeometry(QtCore.QRect(20, 20, 121, 30))
        self.label_order_summary.setObjectName("label_order_summary")
        self.order_summary_content = QtWidgets.QTextEdit(parent=self.order_detail_area)
        self.order_summary_content.setGeometry(QtCore.QRect(20, 60, 991, 261))
        self.order_summary_content.setReadOnly(True)
        self.order_summary_content.setObjectName("order_summary_content")
        self.label_total = QtWidgets.QLabel(parent=self.order_detail_area)
        self.label_total.setGeometry(QtCore.QRect(20, 350, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_total.setFont(font)
        self.label_total.setObjectName("label_total")
        self.label_discount = QtWidgets.QLabel(parent=self.order_detail_area)
        self.label_discount.setGeometry(QtCore.QRect(20, 325, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(10)
        self.label_discount.setFont(font)
        self.label_discount.setObjectName("label_discount")
        self.pushButtonDone = QtWidgets.QPushButton(parent=self.order_detail_area)
        self.pushButtonDone.setGeometry(QtCore.QRect(400, 670, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButtonDone.setFont(font)
        self.pushButtonDone.setStyleSheet("\n"
"\n"
"QPushButton {\n"
"            background-color:rgb(253, 253, 234);\n"
"            color: rgb(91, 76, 43);\n"
"            \n"
"            border-radius: 20px;\n"
"            padding: 10px;\n"
"            font-size: 16px;\n"
"        }\n"
"        QPushButton:hover {\n"
"            background-color: rgb(216, 203, 164);\n"
"        }")
        self.pushButtonDone.setObjectName("pushButtonDone")
        self.lineEditDiscount = QtWidgets.QLineEdit(parent=self.order_detail_area)
        self.lineEditDiscount.setGeometry(QtCore.QRect(140, 329, 621, 21))
        self.lineEditDiscount.setObjectName("lineEditDiscount")
        self.lineEditTotal = QtWidgets.QLineEdit(parent=self.order_detail_area)
        self.lineEditTotal.setGeometry(QtCore.QRect(90, 350, 491, 20))
        self.lineEditTotal.setObjectName("lineEditTotal")
        self.groupBox = QtWidgets.QGroupBox(parent=self.order_detail_area)
        self.groupBox.setGeometry(QtCore.QRect(10, 380, 981, 221))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(16)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEditName = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditName.setGeometry(QtCore.QRect(170, 39, 781, 31))
        self.lineEditName.setObjectName("lineEditName")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 100, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEditPhone = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditPhone.setGeometry(QtCore.QRect(170, 99, 781, 31))
        self.lineEditPhone.setObjectName("lineEditPhone")
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 160, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lineEditEmail = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditEmail.setGeometry(QtCore.QRect(170, 159, 781, 31))
        self.lineEditEmail.setObjectName("lineEditEmail")
        self.label_6 = QtWidgets.QLabel(parent=self.order_detail_area)
        self.label_6.setGeometry(QtCore.QRect(20, 600, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lineEditAddress = QtWidgets.QLineEdit(parent=self.order_detail_area)
        self.lineEditAddress.setGeometry(QtCore.QRect(180, 599, 781, 31))
        self.lineEditAddress.setObjectName("lineEditAddress")
        self.pushButton_Back = QtWidgets.QPushButton(parent=CheckoutWindow)
        self.pushButton_Back.setGeometry(QtCore.QRect(20, 10, 25, 25))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Back.setFont(font)
        self.pushButton_Back.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.pushButton_Back.setAutoFillBackground(False)
        self.pushButton_Back.setStyleSheet("QPushButton {\n"
"    min-width: 25px;\n"
"    min-height: 25px;\n"
"    max-width: 25px;\n"
"    max-height: 25px;\n"
"    border-radius: 10px; \n"
"    background-color: transparent;\n"
"    color: rgb(173, 162, 139);\n"
"    border: none;\n"
"    qproperty-alignment: \'AlignCenter\';\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 255, 240);\n"
"    min-width: 25px;\n"
"    min-height: 25px;\n"
"    max-width: 25px;\n"
"    max-height: 25px;\n"
"    border-radius: 10px;\n"
"    qproperty-alignment: \'AlignCenter\'; \n"
"}\n"
"")
        self.pushButton_Back.setText("◀")
        self.pushButton_Back.setObjectName("pushButton_Back")
        self.label_payment_method = QtWidgets.QLabel(parent=CheckoutWindow)
        self.label_payment_method.setGeometry(QtCore.QRect(50, 10, 171, 30))
        self.label_payment_method.setObjectName("label_payment_method")

        self.retranslateUi(CheckoutWindow)
        QtCore.QMetaObject.connectSlotsByName(CheckoutWindow)

    def retranslateUi(self, CheckoutWindow):
        _translate = QtCore.QCoreApplication.translate
        CheckoutWindow.setWindowTitle(_translate("CheckoutWindow", "Checkout"))
        self.label_order_summary.setStyleSheet(_translate("CheckoutWindow", "font-size: 16px; font-weight: bold; color: #5b4c2b;"))
        self.label_order_summary.setText(_translate("CheckoutWindow", "Order Details:"))
        self.order_summary_content.setStyleSheet(_translate("CheckoutWindow", "background-color: #fdfae6; border: 1px solid #d8c49c; border-radius: 8px; padding: 6px; font-size: 13px; color: #5b4c2b;"))
        self.label_total.setText(_translate("CheckoutWindow", "Total:"))
        self.label_discount.setText(_translate("CheckoutWindow", "Discount coupon:"))
        self.pushButtonDone.setText(_translate("CheckoutWindow", "Done"))
        self.groupBox.setTitle(_translate("CheckoutWindow", "Customer Details:"))
        self.label_2.setText(_translate("CheckoutWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Customer Name:</span></p></body></html>"))
        self.label_3.setText(_translate("CheckoutWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Customer Phone:</span></p></body></html>"))
        self.label_5.setText(_translate("CheckoutWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Customer email:</span></p></body></html>"))
        self.label_6.setText(_translate("CheckoutWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Customer address:</span></p><p><br/></p></body></html>"))
        self.label_payment_method.setStyleSheet(_translate("CheckoutWindow", "font-size: 16px; font-weight: bold; color: #5b4c2b;"))
        self.label_payment_method.setText(_translate("CheckoutWindow", "PAYMENT METHOD"))
