# Form implementation generated from reading ui file 'D:\FinalProject\Ui\ManagerLogin.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LoginMainWindow(object):
    def setupUi(self, LoginMainWindow):
        LoginMainWindow.setObjectName("LoginMainWindow")
        LoginMainWindow.resize(439, 208)
        self.centralwidget = QtWidgets.QWidget(parent=LoginMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutMain = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayoutMain.setObjectName("verticalLayoutMain")
        self.labelTitle = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelTitle.setObjectName("labelTitle")
        self.verticalLayoutMain.addWidget(self.labelTitle)
        self.groupBoxLoginInfo = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBoxLoginInfo.setObjectName("groupBoxLoginInfo")
        self.formLayoutLogin = QtWidgets.QFormLayout(self.groupBoxLoginInfo)
        self.formLayoutLogin.setObjectName("formLayoutLogin")
        self.labelUsername = QtWidgets.QLabel(parent=self.groupBoxLoginInfo)
        self.labelUsername.setObjectName("labelUsername")
        self.formLayoutLogin.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelUsername)
        self.lineEditUsername = QtWidgets.QLineEdit(parent=self.groupBoxLoginInfo)
        self.lineEditUsername.setObjectName("lineEditUsername")
        self.formLayoutLogin.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEditUsername)
        self.labelPassword = QtWidgets.QLabel(parent=self.groupBoxLoginInfo)
        self.labelPassword.setObjectName("labelPassword")
        self.formLayoutLogin.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelPassword)
        self.lineEditPassword = QtWidgets.QLineEdit(parent=self.groupBoxLoginInfo)
        self.lineEditPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.formLayoutLogin.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEditPassword)
        self.verticalLayoutMain.addWidget(self.groupBoxLoginInfo)
        self.horizontalLayoutButtons = QtWidgets.QHBoxLayout()
        self.horizontalLayoutButtons.setObjectName("horizontalLayoutButtons")
        self.pushButtonLogin = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonLogin.setObjectName("pushButtonLogin")
        self.horizontalLayoutButtons.addWidget(self.pushButtonLogin)
        self.pushButtonExit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonExit.setObjectName("pushButtonExit")
        self.horizontalLayoutButtons.addWidget(self.pushButtonExit)
        self.verticalLayoutMain.addLayout(self.horizontalLayoutButtons)
        LoginMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=LoginMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 439, 21))
        self.menubar.setObjectName("menubar")
        LoginMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=LoginMainWindow)
        self.statusbar.setObjectName("statusbar")
        LoginMainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(LoginMainWindow)
        self.pushButtonExit.clicked.connect(LoginMainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(LoginMainWindow)

    def retranslateUi(self, LoginMainWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginMainWindow.setWindowTitle(_translate("LoginMainWindow", "Login System"))
        self.labelTitle.setStyleSheet(_translate("LoginMainWindow", "font: 16pt \"MS Shell Dlg 2\";"))
        self.labelTitle.setText(_translate("LoginMainWindow", "Manager Login System"))
        self.groupBoxLoginInfo.setTitle(_translate("LoginMainWindow", "Login Information"))
        self.labelUsername.setText(_translate("LoginMainWindow", "Username:"))
        self.labelPassword.setText(_translate("LoginMainWindow", "Password:"))
        self.pushButtonLogin.setText(_translate("LoginMainWindow", "Login"))
        self.pushButtonExit.setText(_translate("LoginMainWindow", "Exit"))
