# Form implementation generated from reading ui file 'E:\Git_TDLT\FinalProject\Ui\Ready_to_order.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1085, 784)
        MainWindow.setStyleSheet("background-color: rgb(245, 245, 220);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_logo = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_logo.setGeometry(QtCore.QRect(880, -10, 181, 71))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        self.label_logo.setFont(font)
        self.label_logo.setStyleSheet("background-color:transparent;")
        self.label_logo.setText("")
        self.label_logo.setPixmap(QtGui.QPixmap("E:\\Git_TDLT\\FinalProject\\Ui\\../images/image-removebg-preview (24).png"))
        self.label_logo.setScaledContents(True)
        self.label_logo.setObjectName("label_logo")
        self.pushButton_takeaway = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_takeaway.setGeometry(QtCore.QRect(190, 160, 291, 341))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButton_takeaway.setFont(font)
        self.pushButton_takeaway.setStyleSheet("QPushButton {\n"
"    background-color: rgb(230, 215, 185);\n"
"    color: rgb(71, 71, 71);\n"
"    border-radius: 20px; \n"
"      border:2px solid #FFFFFF;\n"
"    padding: 10px;\n"
"    padding-bottom: 100px;\n"
"    font-size: 18px;\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #D9C9A7; \n"
"}\n"
"\n"
"\n"
"QPushButton:checked {\n"
"    background-color: #C5A673; \n"
"    color: white;\n"
"    border: 2px solid #A67C52;\n"
"}\n"
"")
        self.pushButton_takeaway.setObjectName("pushButton_takeaway")
        self.pushButton_eatin = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_eatin.setGeometry(QtCore.QRect(530, 160, 291, 341))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButton_eatin.setFont(font)
        self.pushButton_eatin.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(230, 215, 185);\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: #4A4A4A;\n"
"    border-radius: 20px; \n"
"      font-size: 18px;\n"
"    padding: 10px;\n"
"    padding-bottom: 100px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #D9C9A7; \n"
"}\n"
"\n"
"\n"
"QPushButton:checked {\n"
"    background-color: #C5A673; \n"
"    color: white;\n"
"    border: 2px solid #A67C52;\n"
"}\n"
"")
        self.pushButton_eatin.setObjectName("pushButton_eatin")
        self.label_take = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_take.setGeometry(QtCore.QRect(280, 310, 111, 121))
        self.label_take.setStyleSheet("background-color:transparent")
        self.label_take.setText("")
        self.label_take.setPixmap(QtGui.QPixmap("E:\\Git_TDLT\\FinalProject\\Ui\\../images/img_4.png"))
        self.label_take.setScaledContents(True)
        self.label_take.setObjectName("label_take")
        self.label_eatin = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_eatin.setGeometry(QtCore.QRect(587, 278, 181, 191))
        self.label_eatin.setStyleSheet("background-color:transparent;")
        self.label_eatin.setText("")
        self.label_eatin.setPixmap(QtGui.QPixmap("E:\\Git_TDLT\\FinalProject\\Ui\\../images/image-removebg-preview (55).png"))
        self.label_eatin.setScaledContents(True)
        self.label_eatin.setObjectName("label_eatin")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1085, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_takeaway.setText(_translate("MainWindow", "TAKE AWAY"))
        self.pushButton_eatin.setText(_translate("MainWindow", "EAT IN"))
